version: '3'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - book-service
      - author-service

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"

  book-service:
    build: ./book-service
    ports:
      - "3002:3002"

  author-service:
    build: ./author-service
    ports:
      - "3003:3003"
