http:
  apiEndpoints:
    users:
      paths: '/users*'
      methods: ['GET', 'POST']
      serviceEndpoint: 'user-service'
    books:
      paths: '/books*'
      methods: ['GET']
      serviceEndpoint: 'book-service'
    authors:
      paths: '/authors*'
      methods: ['POST']
      serviceEndpoint: 'author-service'
  serviceEndpoints:
    user-service:
      url: 'http://user-service:3001/'
    book-service:
      url: 'http://book-service:3002/' 
    author-service:
      url: 'http://author-service:3003/' 
